# iTwin.js Docs CI Build

trigger:
  branches:
    include:
      - master
      - release/*
    exclude:
      - release/2*
      - release/1*

pr:
  drafts: false
  branches:
    include:
      - master
      - release/*
    exclude:
      - release/2*
      - release/1*
  paths:
    exclude:
      - .github/CODEOWNERS

jobs:
  - job:
    workspace:
      clean: all
    pool:
      name: iModelTechCI
      demands: Agent.OS -equals Windows_NT

    steps:
      - template: ../templates/docs-build.yaml
        parameters:
          workingDir: $(Pipeline.Workspace)/itwinjs-core
          outputDir: $(Agent.BuildDirectory)/tempDocsBuild/public_build

      - publish: $(Agent.BuildDirectory)/tempDocsBuild/
        artifact: DocsBuild
        displayName: Publish Pipeline Artifact - DocsBuild
        condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release')))
