# iTwin.js Core CI Build

trigger:
  - master
  - release/*

pr:
  autoCancel: true
  drafts: false
  branches:
    include:
      - master
      - release/*

# jobs:
#   - template: ci-core.yaml
#     parameters:
#       name: Node_16
#       nodeVersion: 16.13.0
#       pool:
#         name: $(name)
#         demands:
#           - Agent.OS -equals $(platform)

jobs:
- job:
  variables:
  - name: linuxPool
    value: 'iModeljs Linux'
  - name: mac_pool
    value: iModelTechCI
  - name: win_pool
    value: iModelTechCI

  strategy:
    matrix:
      "Windows_Node_16":
        OS: windows-latest
        platform: Windows_NT
        name: $(win_pool)
      "Linux_Node_16":
        OS: ubuntu-latest
        platform: Linux
        name: $(linux_pool)
      "MacOS_Node_16":
        OS: macOS-latest
        platform: Darwin
        name: $(mac_pool)

  pool:
    name: $(name)
    demands:
      - Agent.OS -equals $(platform)

  timeoutInMinutes: 120

  workspace:
    clean: all

  steps:
  - checkout: self
  - template: templates/core-build.yaml
    parameters:
      nodeVersion: 16.13.0
