# iTwin.js Core CI Build
#
# This build is used to validate all fork-based PRs and run on a schedule to provide the build status in the README.
#
# It runs on the Hosted Azure Pipelines machines which are slow building the code in the repo, especially the test-apps
# which require several webpacking steps. Due to the time it takes to run, these are only used in a limited number of cases.
#
# The main CI build used is the ./jobs/fast-ci.yaml due to it running on a set of faster machines. However, those are currently
# only available to members of the iTwin GitHub Organization for security reasons. This may change in the future but for now
# the limitation will exist.
#
# This build is not automatically queued for fork-based PRs and needs to be manually triggered by using a comment trigger in the PR.
# Anyone in the iTwin Org can trigger this pipeline by adding this comment,
#   `/azp run imodeljs.imodeljs`

trigger: none
pr: none
schedules:
  - cron: "0 5 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - master
        - releases/*

# jobs:
#   - template: jobs/ci-core.yaml
#     parameters:
#       name: Node_16
#       nodeVersion: 16.13.0
#       pool:
#         vmImage: $(OS)

jobs:
# - job:
#   strategy:
#     matrix:
#       "Windows_Node_16":
#         OS: windows-latest
#         platform: Windows_NT
#         name: $(win_pool)
#       "Linux_${{ parameters.name }}":
#         OS: ubuntu-latest
#         platform: Linux
#         name: $(linux_pool)
#       "MacOS_${{ parameters.name }}":
#         OS: macOS-latest
#         platform: Darwin
#         name: $(mac_pool)

#   pool:
#     vmImage: $(OS)

#   timeoutInMinutes: 120

#   workspace:
#     clean: all

#   steps:
#   - template: jobs/ci-core.yaml
#       parameters:
#         nodeVersion: 16.13.0
#         gitRepo: self
#         gitBranch: master

  - job: Windows
    pool:
      vmImage: windows-latest
  steps:
  - template: jobs/ci-core.yaml
      parameters:
        nodeVersion: 16.13.0
        gitRepo: self
        gitBranch: master

  - job: Linux
    pool:
      vmImage: ubuntu-latest
  steps:
  - template: jobs/ci-core.yaml
      parameters:
        nodeVersion: 16.13.0
        gitRepo: self
        gitBranch: master

  - job: Mac
    pool:
      vmImage: macOS-latest
  steps:
  - template: jobs/ci-core.yaml
      parameters:
        nodeVersion: 16.13.0
        gitRepo: self
        gitBranch: master


