# The template defines the primary steps for creating the TypeDoc API files, gathering other md files,
# and running a step to combine everything.

parameters:
  - name: workingDir
    type: string
    default: $(Pipeline.Workspace)/itwinjs-core
  - name: stagingDir
    type: string
    default: $(System.ArtifactsDirectory)/staging
  - name: outputDir
    type: string
    default: $(Pipeline.Workspace)/tempDocsBuild/public_build
  - name: downloadCurrentBuildArtifacts
    type: boolean
    default: false
  - name: shouldPublish
    type: boolean
    default: false

variables:
  tempDocsLocation: $(Pipeline.Workspace)/tempDocsBuild

jobs:
  - job:
    workspace:
      clean: all
    pool:
      name: iModelTechCI
      demands: Agent.OS -equals Windows_NT

steps:
  - checkout: self
    path: itwinjs-core
    clean: true

  - task: NodeTool@0
    displayName: Use Node 14
    inputs:
      versionSpec: 14.17.4
      checkLatest: true

  - script: |
      git config --local user.email imodeljs-admin@users.noreply.github.com
      git config --local user.name imodeljs-admin
    displayName: Setup git config

  - script: node common/scripts/install-run-rush.js install
    displayName: rush install
    workingDirectory: ${{ parameters.workingDir }}

  - script: node common/scripts/install-run-rush.js build:ci
    displayName: rush build
    workingDirectory: ${{ parameters.workingDir }}

  - script: node common/scripts/install-run-rush.js docs
    displayName: rush docs
    workingDirectory: ${{ parameters.workingDir }}

  # Gathers all the pieces to run BeMetalsmith
  - template: ../../templates/gather-docs.yaml
    parameters:
      workingDir: ${{ parameters.workingDir }}
      stagingDir: ${{ parameters.stagingDir }}
      downloadCurrentBuildArtifacts: ${{ parameters.downloadCurrentBuildArtifacts }}

  # Currently BeMetalsmith is an internal only tool
  - script: npm install @bentley/bemetalsmith@4.x
    displayName: Install BeMetalsmith
    workingDirectory: ${{ parameters.workingDir }}

  - script: "./node_modules/.bin/bmsBuild --strictLinkChecking --topicsMustHaveDesc --source ${{ parameters.stagingDir }} --destination ${{ parameters.outputDir }} --siteTitle iTwin.js"
    displayName: Run bmsBuild
    workingDirectory: ${{ parameters.workingDir }}

  # Update the .updated.json file after the bmsBuild
  - publish: ${{ parameters.stagingDir }}/config/.updated.json
    artifact: .updated.json
    displayName: Publish Pipeline Artifact - .updated.json
    condition: and(succeeded(), eq('${{ parameters.downloadCurrentBuildArtifacts }}', false))

  - publish: $(tempDocsLocation)
    artifact: DocsBuild
    displayName: Publish Pipeline Artifact - DocsBuild
    condition: and(succeeded(), {{ parameters.shouldPublish }})

  # Extra stuff

  - task: DownloadPipelineArtifact@2
    displayName: 'Download Pipeline Artifact - Nuget Spec'
    inputs:
      buildType: specific
      project: '2c48216e-e72f-48b4-a4eb-40ff1c04e8e4'
      definition: 1830
      buildVersionToDownload: specific
      pipelineId: 1234689

  - task: qetza.replacetokens.replacetokens-task.replacetokens@3
    displayName: 'Replace tokens in NugetPackage.nuspec'
    inputs:
      targetFiles: '$(Pipeline.Workspace)\DocsNugetSpecFile\NugetPackage.nuspec'

  - task: DeleteFiles@1
    displayName: 'Delete landing page '
    inputs:
      SourceFolder: '$(tempDocsLocation)\public_build'
      Contents: index.html

  - task: NuGetToolInstaller@1
    inputs:
      versionSpec: 4.9.2

  - task: NuGetCommand@2
    displayName: 'NuGet pack'
    inputs:
      command: pack
      packagesToPack: '$(Pipeline.Workspace)\DocsNugetSpecFile\NugetPackage.nuspec'
      versioningScheme: byBuildNumber
